# -*- coding: utf-8 -*-
"""Yash Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FA_1KHJznLSsfBMYZD0aHb9N7UXWoQpt
"""

import matplotlib.pyplot as plt
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]
plt.plot(x,y)
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.title('Simple Line Plot')
plt.show()

import matplotlib.pyplot as plt
Categories = ['Student A', 'Student B', 'Student C']
Values = [85, 90, 78]
plt.plot(Categories,Values)
plt.xlabel('Students')
plt.ylabel('scores')
plt.title('Student Scores')
plt.show()



import matplotlib.pyplot as plt
heights = [150, 160, 170, 180, 190]
weights = [50, 60, 65, 80, 85]
plt.scatter(heights,weights)
plt.xlabel('Heights')
plt.ylabel('Weights')
plt.title('Heights vs Weights')
plt.show()

import matplotlib.pyplot as plt
time = [1, 2, 3, 4, 5]
temperature = [30, 32, 35, 33, 31]
plt.plot(time,temperature)
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.title('Temperature Over Time')
plt.show()

import matplotlib.pyplot as plt
Categories =['Red', 'Blue', 'Green', 'Yellow']
Values = [10, 20, 15, 5]
plt.plot(Categories,Values)
plt.xlabel('Colors')
plt.ylabel('Number of People')
plt.title('Favorite Colors')
plt.show()

import matplotlib.pyplot as plt
age = [10, 12, 14, 16, 18]
height = [140, 145, 150, 160, 170]
plt.scatter(age,height)
plt.xlabel('Age')
plt.ylabel('Height')
plt.title('Age vs Height')
plt.show()

import matplotlib.pyplot as plt
x = [1, 2, 3, 4]
y = [1, 4, 9, 16]
plt.plot(x, y, color='red', linestyle='--')
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.title('Customizing Line Plot with colors & style')
plt.show()

import matplotlib.pyplot as plt
Categories =['January', 'February', 'March']
Values =[300, 400, 350]
plt.plot(Categories,Values)
plt.xlabel('Months')
plt.ylabel('Sales')
plt.title('Monthly Sales')
plt.show()

import matplotlib.pyplot as plt
English = [80, 85, 88, 90]
Marathi = [70, 78, 85, 87]
plt.scatter(English,Marathi)
plt.xlabel('English')
plt.ylabel('Marathi')
plt.title('Test Scores Comparison')
plt.show()

import matplotlib.pyplot as plt
x = [0, 1, 2, 3, 4]
y = [0, 1, 4, 9, 16]
plt.plot(x,y)
plt.xlabel('Input')
plt.ylabel('Output')
plt.title('Input vs Output')
plt.show()